### ISSUE TITLE
MVP List and Schema

### ISSUE THREAD

**Issue by BCrawfordScott** [lordrickyz/Jello#1]
Great work, @lordrickyz .  Overall you've got good structure here.  I would suggest narrowing the scope of your MVPs just a little to really focus in on the core functionality of each feature. Your PM will be able to help you zoom in on precisely what needs to get done.

# MVP
- Expand on the features that a user cannot use unless logged in: what can they do, what can't they do?  Remember that this will be a rolling feature since user auth is first and cannot limit features that don't yet exist.
- Typo: "Boards should be able to see their boards"
- What is the immediate use of archiving a list?  Could this be a bonus feature? Same with Cards?
- Add Drag and Drop as either a bonus, or a core element of the list and cards feature.

As a suggestion, you might want to swap numbers 5 and 6.  Sharing is more intricate than commenting with not as much immediate payoff.

# Schema
- Remove member_id from the board table and create a joins table called something like `board_memberships`.  That way, a board can have many memberships and users can have many board_memberships.

**Comment by lordrickyz** [comment]
Thank you for your feedback. 

MVP CheckList

--------

> Expanded and explained features that guests/demo users should be able to do.
> Fixed Typo.
> Switched to bonus feature for now. Archiving - I believe would possibly be toggling hide class to make post invisible.
> Added Drag and Drop as bonus since additional library is needed to discover.
> Swapped number 5 and 6. 

--------

Schema Check List
>Created board_membership table for connecting relationships with user and board.
