### ISSUE TITLE
Design Doc Review #3

### ISSUE THREAD

**Issue by BCrawfordScott** [lordrickyz/Jello#3]
# Backend Routes
- [x] Should users be able to delete lists?
- [x] Should users be able to delete cards?

# Frontend Routes
- If NOT logged in, should a user be able to see a specific board as indicated by your FE routes?
- You can use the routes listed to launch modals for you if you like for the creation of lists, cards, and comments, but you can also just use the UI slice of state in redux.  Either way is fine, but Redux will look cleaner.

Great work on these docs.  You've got a solid foundation here.  If you aim to add drag and drop functionality talk to a TA about using the React Drag and Drop library (or do it yourself if you're feeling up for a challenge!) But save it for a bonus unless you feel really strongly about it.

**Comment by lordrickyz** [comment]
Thanks for reviewing my backend and frontend routes.
I will fix them on the go while writing out my board routes and db.

>React Drag and Drop
* Cool, I'll ask a TA if I need help but that will be a bonus if I can get through my boards and list functions first.

**Comment by lordrickyz** [comment]
* Added delete routes for cards and list

Will check to see if routes needs to be nested on the go.
