### ISSUE TITLE
Auth review

### ISSUE THREAD

**Issue by aracpyon** [lordrickyz/Jello#4]
Hi Ricky, great job on your auth! Here are my reviews:

- [x] Trello is handling the error messages little differently. Please change like this:
![Screen Shot 2020-06-04 at 2 33 54 PM](https://user-images.githubusercontent.com/56740477/83797720-101be400-a671-11ea-9644-9d58008399a6.png)

- [x] Trello automatically sends you to the sign up page if the user wrote a new email on the login page. I think you can do this but for now, just make error messages in the same way with the sign up page and if you have time, let's fix this.

**Comment by lordrickyz** [comment]
> Had a discussion with Ara about Trello Error Handling
* Found Trello has two redirections of sign up pages.
  * One's for Trello.com and the other is for id.atlassen.com as seen on Ara's attached Image in URL

In regards to fixing it, we went with trello.com/login and /signup pages instead of id.atlassen as that could potentially be a future bonus addition for better error handling[displays], security and password strength detection measurements.

**Comment by kkossally** [comment]
- Nice job overall. Tackle the following tasks to make it even better. Feel free to leave comments on this issue if you have questions. Make sure to Slack me if you do so to make sure I answer them in a timely fashion.

- [ ] Address the warnings in the console on the splash page

- [ ] When you implement the dashboard feature, make sure to style the welcome message in the header accordingly

- [ ] Style the session error pop-ups and messages to match as much as you can

- I agree with Ara that you should implement the error styles of the parent website as much as you can within reason. So, no need to implement strong password checks or redirecting to another site, but do as much as you think is reasonable.

- [ ] Make sure to update the personal links at the bottom when you have them ready

- Good work on the splash page styling; it's clean and modern-looking. To get closer to pixel perfect: 

- [ ] Match the height, spacing and text size of the top part of your splash to Trello's

- [ ] Match the box shadow on the sticky header on the original site

- [ ] Match the header transitions as you scroll down the splash page

- [ ] Consider replacing the current screenshots of app features with your own app's screenshots when those features have been implemented. The current image resolutions are a bit off.

- I appreciate the cheekiness of "Sign up and become one of the few around the world to use Jello", but know that recruiters may not share your sense of humor or even be paying enough attention to see the humor in it and not count it as a mistake.
